### PR TITLE
Add support for viewing images by tags

### PR DESCRIPTION
**Pull request by abrenoch**
Adds a menu at the top right of the root category view page which contains button to open a tag selection sheet, a dedicated page for viewing tagged images, and updates the gallery view to support loading tagged images.

This also includes the code for favorite image sets, but has been disabled for the time being (perhaps makes sense to include once images can be added/removed from favorites from the app). There are also some commented-out menu items that reflect how the ios version is organized, but didn't want to include more than I already have in this PR.

Please note the changes in `CategoryViewPage` - I made an effort to make the image grid reusable for other view types (in `views/components/content_grid.dart`). Currently being used in the `FavoritesViewPage` and `TagFiewPage` as well.

image
image
image

### CODE REVIEW

**Comment by abrenoch** [comment]
Note: e68f133698d26db847608ffbcf0a6ee2adf63020 was incorrectly titled 'removed root category view page' rather than 'removed root tag view page'

**Comment by remi-martin** [comment]
I'll try your PR in time. Thanks for your contribution.

**Comment by abrenoch** [comment]
Just a heads up I merged the recent changes to the `master` branch into this one. One odd thing I ran into was somehow the flutter_slidable library had somehow found itself on version 1.3.1, despite the pubspec calling out `^1.1.0`... No idea how that happened! 

I asked for help about it here: https://github.com/flutter/flutter/issues/107393 and was tipped off to upgrade to 1.3.2...

Which worked, but when I switched back to master and did a `pub upgrade` (to make a new branch with the version bump), things seemed to be working as expected. A little weird but seems to be working correctly now! Maybe worth considering a bump to `flutter_slidable`!

**Comment by remi-martin** [comment]
Alright, I'll try this on my side :+1:

**Comment by remi-martin** [comment]
Hi, this PR is now obsolete because of the 2.0 development. However, I still want to add this feature, so I'll follow your work for that.

**Comment by abrenoch** [comment]
> Hi, this PR is now obsolete because of the 2.0 development. However, I still want to add this feature, so I'll follow your work for that.

Hey @remi-martin hope all is well. I found myself with some free time and started updating the code for this to be congruent with your recent changes - just wanted to let you know if you were still considering this for future implementation!

**Comment by remi-martin** [comment]
Hi, I still plan to add this feature to the app.

I just need to test it, and it might be included in next release of Piwigo NG.

**Pull request merged**
