### PR TITLE
WIP: App Drawer, Tags & Favorites

### PR DESCRIPTION
**Pull request by abrenoch**
This is just a preview of some changes I was working on - it isn't intended to be an actual PR at the moment. Would love to see them merged, but if you have a different direction in mind I get it.

1. Add an app drawer for navigating between albums/tags/favorites lists
2. Adds a root tag view page (where tags can be managed)
3. Adds a tagged images page
4. Adds a favorites images page (accessible if logged in)
5. Added `TagsAPI.getTags`, `ImagesAPI.fetchTagImages` and `ImagesAPI.fetchTagImages` methods
6. Added `PageRouter` and `PageArguments` - moves router logic out of `main.dart`
7. Added dialog for editing tags

image
image

### CODE REVIEW

**Comment by remi-martin** [comment]
Hi, thanks a lot for your contribution. However, we do not want to change the design of the application as we want to keep Piwigo iOS design for now. Please see [Piwigo App Store](https://apps.apple.com/fr/app/piwigo/id472225196).

**Comment by remi-martin** [comment]
Concerning Tags and Favorites features, they can be accessed through the top right button (with 3 dots) on iOS, which opens a dropdown instead of a drawer.

**Comment by abrenoch** [comment]
Hey thanks for the feedback @remi-martin, I didn't realize it was being modeled after the ios version. Aside from the drawer, seems like the other work may still be applicable - would you be open to me reworking this a bit (in a different branch without the drawer stuff) to be more like the ios version?

**Comment by remi-martin** [comment]
> seems like the other work may still be applicable
I totally agree with you.

> would you be open to me reworking this a bit (in a different branch without the drawer stuff) to be more like the ios version?
I'll see what I can do for that but be sure that your help is really appreciated ;)

**Comment by remi-martin** [comment]
Hey ! Sorry for the delay, I'm working only 3 days a week on this project. 

I talked about this PR with the Piwigo Team. For us, what is mandatory for the app are the upload features and all of what concern the administration of a Piwigo server. So, filtering images per tags or checking the favorites is not what we are looking for right now. 

However, those features are still interesting, which is why I encourage you to continue your work if you want (on this PR or another). I'll be available here on Github if there is anything you need but I wont directly work on it as it is not my priority now.

I'll provide you some screens of the iOS implementation of the Tags and Favorites pages ASAP.

Best regards,
Rémi.

**Comment by abrenoch** [comment]
Hey @remi-martin no problem! I understand the team has their priorities set; I use piwigo as more of a media hub rather than a photo backup solution so my interests might not be that of typical users. I'll definitely keep fiddling around here, I don't mind running some experimental branches 😁. I have chromecast support in one of them - allowing the app to work as a remote control for it.

Some screenshots of how ios is set up would certainly be appreciated, I didn't want to nag my friends to install an app so I could look at it haha.

**Comment by remi-martin** [comment]
Hi, here are some screens from the iOS App:

iOS Front page
This is the main page on iOS, the menu can be opened with the top right button.

iOS Menu
The menu contains Favorites, Tags and more features.

iOS Tags
This is the list of all tags that are used in the Piwigo (unused tags aren't shown which is weird).

iOS Tags images
When we tap on a tag it opens a new page with the list of all the files linked to this tag.

Hope this helps ;)

**Comment by abrenoch** [comment]
Certainly, thanks! I'll be in touch if I have any questions!

**Comment by abrenoch** [comment]
Hey @remi-martin, would appreciate some feedback when you have a moment.

I was looking into revising some of the components to be more reusable (the image grid specifically here), as to keep the amount of redundant code to a minimum... I wanted to run this change by you before I roll with it.

I added a `ContentGrid` widget here: 104b8d639a0ef362e3729911ed57e26934fc7ae0 and implemented it into the `CategoryViewPage` here b059984f0dfb2d96d86424c9abe376c51b22bea3. 

I just wanted to get another set of eyes on this when you have time!

**Pull request closed without merging**
